# Generated by Django 5.2.11 on 2026-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_app_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
