# Generated by Django 5.2.11 on 2026-02-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='operator_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
