# Generated by Django 5.2.11 on 2026-03-12 05:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorytransaction_operator_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('machine_name', models.CharField(db_index=True, max_length=150)),
                ('cupboard_no', models.CharField(db_index=True, max_length=50)),
                ('rack_no', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('vendor_name', models.CharField(db_index=True, max_length=255)),
                ('vendor_contact', models.CharField(blank=True, max_length=20)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('vendor_address', models.TextField(blank=True)),
                ('maintenance_category', models.CharField(blank=True, max_length=100, null=True)),
                ('material_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_code'], name='inventory_i_item_co_d93027_idx'), models.Index(fields=['machine_name'], name='inventory_i_machine_353f58_idx'), models.Index(fields=['vendor_name'], name='inventory_i_vendor__cb326d_idx'), models.Index(fields=['created_at'], name='inventory_i_created_c50f70_idx')],
            },
        ),
    ]
