# Generated by Django 5.2.11 on 2026-02-18 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
    ]
