# Generated by Django 5.2.11 on 2026-02-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('STOCK_ADDED', 'Stock Added'), ('STOCK_USED', 'Stock Used'), ('LOW_STOCK', 'Low Stock'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
    ]
