import * as XLSX from "xlsx";

export function exportToExcel(data: Record<string, string | number>[], fileName: string) {
  const ws = XLSX.utils.json_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Report");
  XLSX.writeFile(wb, `${fileName}.xlsx`);
}

export function printPdfReport(content: string, title: string, filterSummary: string, generatedBy?: string) {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(`
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: Inter, sans-serif; padding: 40px; color: #1a2e3d; }
        .header { display: flex; align-items: center; gap: 16px; margin-bottom: 8px; border-bottom: 2px solid #0B3C5D; padding-bottom: 16px; }
        .header img { height: 40px; }
        .header-text h1 { font-size: 18px; margin: 0; color: #0B3C5D; }
        .header-text p { font-size: 12px; margin: 2px 0 0; color: #666; }
        .meta { font-size: 11px; color: #666; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th { background: #f0f2f5; padding: 8px 12px; text-align: left; font-weight: 600; border-bottom: 2px solid #d0d5dd; text-transform: uppercase; font-size: 10px; letter-spacing: 0.5px; }
        td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
        .footer { margin-top: 24px; font-size: 10px; color: #999; border-top: 1px solid #e5e7eb; padding-top: 12px; }
        .signature { margin-top: 32px; font-size: 11px; color: #333; border-top: 1px solid #e5e7eb; padding-top: 12px; }
        .print-btn { background: #0B3C5D; color: white; border: none; padding: 8px 24px; font-size: 12px; cursor: pointer; margin-bottom: 20px; }
        @media print { .print-btn { display: none; } }
      </style>
    </head>
    <body>
      <button class="print-btn" onclick="window.print()">Print Report</button>
      <div class="header">
        <div class="header-text">
          <h1>Godrej Aerospace</h1>
          <p>${title}</p>
        </div>
      </div>
      <div class="meta">
        <p>Generated: ${new Date().toLocaleString()}</p>
        <p>${filterSummary}</p>
      </div>
      ${content}
      <div class="signature">
        <p><strong>Generated By:</strong> ${generatedBy || "System"}</p>
        <p><strong>Generated On:</strong> ${new Date().toLocaleString()}</p>
        <p><strong>Approved By:</strong> High Authority</p>
      </div>
      <div class="footer">
        <p>© Godrej Aerospace – Internal Use Only | Page 1</p>
      </div>
    </body>
    </html>
  `);
  win.document.close();
}
